#!/usr/bin/env python3
"""
AING Semantic Model Generator
Usage: python generate.py
Reads: semantic/semantic_model.yaml
Writes:
  generated/ddl/schema.sql
  generated/pydantic_models.py
  dbt/models/schema.yml
"""
import re
import sys
from pathlib import Path
import yaml

ROOT = Path(__file__).parent
SEMANTIC = ROOT / "semantic" / "semantic_model.yaml"
DDL_OUT = ROOT / "generated" / "ddl" / "schema.sql"
PYDANTIC_OUT = ROOT / "generated" / "pydantic_models.py"
DBT_OUT = ROOT / "dbt" / "models" / "schema.yml"

PG_TYPE_MAP = {
    "uuid": "UUID",
    "string": "TEXT",
    "timestamp": "TIMESTAMPTZ",
    "boolean": "BOOLEAN",
    "date": "DATE",
    "enum": "VARCHAR(50)",
    "integer": "INTEGER",
}

PY_TYPE_MAP = {
    "uuid": "UUID",
    "string": "str",
    "timestamp": "datetime",
    "boolean": "bool",
    "date": "date",
    "integer": "int",
}


def _spec(col_def) -> dict:
    """Normalize attribute: shorthand string or full dict."""
    return col_def if isinstance(col_def, dict) else {"type": col_def}


def _pg_col(name: str, spec: dict) -> str:
    col_type = spec.get("type", "string")
    max_len = spec.get("max_length")

    if col_type == "enum":
        pg_type = "VARCHAR(50)"
    elif col_type == "string" and max_len:
        pg_type = f"VARCHAR({max_len})"
    else:
        pg_type = PG_TYPE_MAP.get(col_type, "TEXT")

    null_str = " NOT NULL" if not spec.get("nullable", False) else ""

    default = spec.get("default")
    if default is None:
        default_str = ""
    elif isinstance(default, bool):
        default_str = f" DEFAULT {'true' if default else 'false'}"
    elif isinstance(default, str):
        default_str = f" DEFAULT '{default}'"
    else:
        default_str = f" DEFAULT {default}"

    return f"    {name} {pg_type}{null_str}{default_str}"


def generate_ddl(model: dict) -> str:
    lines = [
        "-- GENERATED BY generate.py — DO NOT EDIT",
        "-- Source: semantic/semantic_model.yaml",
        "",
    ]
    for entity_name, entity in model["entities"].items():
        table = entity["source_table"]
        cols, constraints = [], []

        for col_name, col_def in entity["attributes"].items():
            spec = _spec(col_def)
            cols.append(_pg_col(col_name, spec))

            if spec.get("unique"):
                constraints.append(
                    f"    CONSTRAINT uq_{table}_{col_name} UNIQUE ({col_name})"
                )
            if spec.get("type") == "enum":
                vals = ", ".join(f"'{v}'" for v in spec.get("values", []))
                constraints.append(
                    f"    CONSTRAINT chk_{table}_{col_name} CHECK ({col_name} IN ({vals}))"
                )
            ref = spec.get("references")
            if ref:
                ref_entity, ref_col = ref.split(".")
                ref_table = model["entities"][ref_entity]["source_table"]
                constraints.append(
                    f"    CONSTRAINT fk_{table}_{col_name}"
                    f" FOREIGN KEY ({col_name}) REFERENCES {ref_table}({ref_col})"
                )

        for test in entity.get("tests", []):
            if not isinstance(test, dict):
                continue
            for col_name in test.get("unique", []):
                c = f"    CONSTRAINT uq_{table}_{col_name} UNIQUE ({col_name})"
                if c not in constraints:
                    constraints.append(c)

        # Identify primary key: first uuid NOT NULL column (always 'id' by convention)
        pk_col = next(
            (name for name, col_def in entity["attributes"].items()
             if _spec(col_def).get("type") == "uuid" and not _spec(col_def).get("nullable", False)),
            None,
        )
        if pk_col:
            constraints.insert(0, f"    CONSTRAINT pk_{table} PRIMARY KEY ({pk_col})")

        body = ",\n".join(cols + constraints)
        lines += [f"CREATE TABLE IF NOT EXISTS {table} (", body, ");\n"]

    return "\n".join(lines)


def generate_pydantic(model: dict) -> str:
    lines = [
        "# GENERATED BY generate.py — DO NOT EDIT",
        "# Source: semantic/semantic_model.yaml",
        "from __future__ import annotations",
        "from uuid import UUID",
        "from datetime import datetime, date",
        "from typing import Literal, Optional",
        "from pydantic import BaseModel, Field",
        "",
    ]
    for entity_name, entity in model["entities"].items():
        rule_comments = "".join(
            f"\n    # {r['id']}: {r['rule']}"
            for r in entity.get("business_rules", [])
        )
        lines.append(f"class {entity_name}(BaseModel):{rule_comments}")

        for col_name, col_def in entity["attributes"].items():
            spec = _spec(col_def)
            col_type = spec.get("type", "string")
            nullable = spec.get("nullable", True)
            default = spec.get("default")
            max_len = spec.get("max_length")

            if col_type == "enum":
                vals_str = ", ".join(f"'{v}'" for v in spec.get("values", []))
                py_type = f"Literal[{vals_str}]"
            else:
                py_type = PY_TYPE_MAP.get(col_type, "str")

            if nullable:
                py_type = f"Optional[{py_type}]"

            field_args = []
            if default is not None:
                if isinstance(default, bool):
                    field_args.append(f"default={default}")
                elif isinstance(default, str):
                    field_args.append(f"default='{default}'")
                else:
                    field_args.append(f"default={default}")
            elif nullable:
                field_args.append("default=None")
            if max_len:
                field_args.append(f"max_length={max_len}")

            field_str = f"Field({', '.join(field_args)})" if field_args else "..."
            lines.append(f"    {col_name}: {py_type} = {field_str}")

        lines.append("")

    return "\n".join(lines)


def generate_dbt_schema(model: dict) -> str:
    _raw = model.get("domain", "app")
    domain = re.sub(r"(?<!^)(?=[A-Z])", "_", _raw).lower()
    tables = []

    for entity_name, entity in model["entities"].items():
        table_name = entity["source_table"]
        col_tests: dict[str, list] = {}

        for test in entity.get("tests", []):
            if not isinstance(test, dict):
                continue
            for c in test.get("not_null", []):
                col_tests.setdefault(c, []).append("not_null")
            for c in test.get("unique", []):
                col_tests.setdefault(c, []).append("unique")

        columns = []
        for col_name, col_def in entity["attributes"].items():
            spec = _spec(col_def)
            tests = list(col_tests.get(col_name, []))

            if not spec.get("nullable", True) and "not_null" not in tests:
                tests.append("not_null")
            if spec.get("unique") and "unique" not in tests:
                tests.append("unique")
            if spec.get("type") == "enum":
                tests.append({"accepted_values": {"values": spec.get("values", [])}})
            ref = spec.get("references")
            if ref:
                ref_entity, ref_col = ref.split(".")
                ref_table = model["entities"][ref_entity]["source_table"]
                tests.append({
                    "relationships": {
                        "to": f"source('{domain}', '{ref_table}')",
                        "field": ref_col,
                    }
                })

            if tests:
                columns.append({"name": col_name, "tests": tests})

        table_entry: dict = {"name": table_name, "columns": columns}

        tables.append(table_entry)

    output = {
        "version": 2,
        "sources": [{"name": domain, "schema": "public", "tables": tables}],
    }
    header = "# GENERATED BY generate.py — DO NOT EDIT\n# Source: semantic/semantic_model.yaml\n"
    return header + yaml.dump(output, default_flow_style=False, sort_keys=False, allow_unicode=True)


def main() -> None:
    if not SEMANTIC.exists():
        print(f"ERROR: {SEMANTIC} not found", file=sys.stderr)
        sys.exit(1)

    model = yaml.safe_load(SEMANTIC.read_text(encoding="utf-8"))

    DDL_OUT.parent.mkdir(parents=True, exist_ok=True)
    DDL_OUT.write_text(generate_ddl(model), encoding="utf-8")
    print(f"[OK] {DDL_OUT}")

    PYDANTIC_OUT.parent.mkdir(parents=True, exist_ok=True)
    PYDANTIC_OUT.write_text(generate_pydantic(model), encoding="utf-8")
    print(f"[OK] {PYDANTIC_OUT}")

    DBT_OUT.parent.mkdir(parents=True, exist_ok=True)
    DBT_OUT.write_text(generate_dbt_schema(model), encoding="utf-8")
    print(f"[OK] {DBT_OUT}")


if __name__ == "__main__":
    main()
